### ISSUE TITLE
Copy paste code samples with firefox does not copy newlines

### ISSUE THREAD

**Issue by MansurAliKoroglu** [supertokens/supertokens-website#172]
### Issue

I copy paste the code blocks (partial or full) like this:

![image](https://user-images.githubusercontent.com/43291306/197981766-3d9bd47b-bf3f-4125-b0cb-3653fe031dbd.png)

This is the result of paste:

![image](https://user-images.githubusercontent.com/43291306/197981920-7209a747-43b5-4936-b86b-2f91a6a81469.png)

I tested this on same OS by using chrome. It works just fine.

### OS Information
![image](https://user-images.githubusercontent.com/43291306/197981292-32f0ba22-c2b7-41fe-83c6-df654b1c4d50.png)

### Browser Information
![image](https://user-images.githubusercontent.com/43291306/197981226-e378aa58-f9fc-4358-b44b-c4b9006fb1f8.png)

**Comment by nkshah2** [comment]
Hi @MansurAliKoroglu,

Thanks for reporting this issue, after digging a little deeper into this it appears its a bug that was introduced in one of the recent updates to Firefox where copying rich text does not preserve its original formatting (especially in code snippets). Since there is nothing specific we can do to solve this I will close this issue, in the meantime the copy button works correctly as you said so I would recommend using that.
